plugins {
    id 'java'
    id 'application'
}

group = 'miniproject'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['image', 'sound', 'file', 'font']
        }
    }
}

application {
    mainClass = 'GameMain'
    applicationDefaultJvmArgs = ['-Dfile.encoding=UTF-8']
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
